services:
  grpc-server:
      build:
        context: .
        dockerfile: ./grpc-server/Dockerfile
      container_name: grpc-server
      ports:
        - "50051:50051"
      depends_on:
        - redis
        - clickhouse
                
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    networks:
      - app-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - CLICKHOUSE_DB=default

  redpanda-connect:
    image: vectorized/redpanda:latest
    container_name: redpanda-connect
    volumes:
      - ./configs/connect.yaml:/app/connect.yaml
      - ./configs/mappings.blobl:/app/mappings.blobl
    environment:
      - RP_CFG_CONNECT_CONFIG=/app/connect.yaml
    # command: ["rpk", "connect", "run", "/app/connect.yaml"]
    depends_on:
      - redis
      - clickhouse
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
